name: test-service

services:
  app:
    image: test-service
    pull_policy: build
    build: .
    develop:
      watch:
        - path: app
          action: sync+restart
          target: /opt/app/app
        - path: requirements
          action: rebuild
        - path: Dockerfile
          action: rebuild
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "curl", "-s", "http://localhost:8041/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "8041:8041"

