[tool.bandit]
format = "custom"
exclude_dirs = [
    "venv",
    ".git", 
    "__pycache__"
]

[tool.bandit.assert_used]
skips = [
    "*/*_test.py",  
    "*/test_*.py"
]

[tool.mypy]
plugins = ["pydantic.mypy"]

strict_optional = true
exclude = ["venv"]
follow_imports = "silent"
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
check_untyped_defs = true
no_implicit_reexport = true
disallow_untyped_calls = true
disallow_incomplete_defs = true
disallow_untyped_defs = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true

